[project]
name = "lstm-medical-model"
version = "0.1.0"
dependencies = [
    "google-cloud-bigquery",
    "google-cloud-storage",
    "torch",
    "numpy",
    "pandas",
    "scikit-learn",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"