[project]
name = "model-container"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gcsfs>=2025.9.0",
    "google-cloud-storage>=3.4.0",
    "pandas>=2.3.3",
]
